// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpNwqORMNxUDB8Nm1HWF5z4JLtnzeOhwY',
    appId: '1:437366564133:web:d6122e9acf04d7c54a66cc',
    messagingSenderId: '437366564133',
    projectId: 'note-app-alert',
    authDomain: 'note-app-alert.firebaseapp.com',
    storageBucket: 'note-app-alert.firebasestorage.app',
    measurementId: 'G-HQPTC6JH3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAU0zoYXNWIzqgejgGbORDXvt_8WsjfxKA',
    appId: '1:437366564133:android:40b624a45919f0cf4a66cc',
    messagingSenderId: '437366564133',
    projectId: 'note-app-alert',
    storageBucket: 'note-app-alert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKlamdPgqwgIIo4588iboxOkanTrl4q1M',
    appId: '1:437366564133:ios:412782ab3619bc794a66cc',
    messagingSenderId: '437366564133',
    projectId: 'note-app-alert',
    storageBucket: 'note-app-alert.firebasestorage.app',
    iosBundleId: 'com.example.frotend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKlamdPgqwgIIo4588iboxOkanTrl4q1M',
    appId: '1:437366564133:ios:412782ab3619bc794a66cc',
    messagingSenderId: '437366564133',
    projectId: 'note-app-alert',
    storageBucket: 'note-app-alert.firebasestorage.app',
    iosBundleId: 'com.example.frotend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpNwqORMNxUDB8Nm1HWF5z4JLtnzeOhwY',
    appId: '1:437366564133:web:f35f0f8f7072a5184a66cc',
    messagingSenderId: '437366564133',
    projectId: 'note-app-alert',
    authDomain: 'note-app-alert.firebaseapp.com',
    storageBucket: 'note-app-alert.firebasestorage.app',
    measurementId: 'G-3TH857N7N4',
  );
}
